name: build_release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Run tests
        run: |
          make test
          make promu
          make check_license

      - name: Build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          promu crossbuild
          promu crossbuild tarballs
          promu checksum .tarballs
          promu release .tarballs

      - name: Push to GHCR.io
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}
          registry: ghcr.io
          username: galexrt
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_names: true

      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          tag_names: true
