name: documentation
on:
  push:
    branches:
      - main

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    container:
      image: "squidfunk/mkdocs-material:latest"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build
        run: |
          mkdocs build --clean

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: ancientt.galexrt.moe
